### ISSUE TITLE
Changing the font size

### ISSUE THREAD

**Issue by LewisSpring** [jeffeb3/OctoPrint-TerminalMessaging#7]
Hi there,

this plugin is very helpful, but I find the font size is too big.
Is there a way to change this?

Thank you

**Comment by LMS0815** [comment]
I assume one can change it via CSS (Themify) as a workaround.

**Comment by LMS0815** [comment]
In addition I would like to have  the _received_ left aligned as it is difficult to read on a wide screen.

![image](https://user-images.githubusercontent.com/8235214/97288892-c3ff5500-1846-11eb-9a88-3d636ed680bf.png)

**Comment by LewisSpring** [comment]
> I assume one can change it via CSS (Themify) as a workaround.

thatd require having Themify installed, though right?
If possible i'd be easier not to have this dependancy.

i've looked around the source files, i've found the CSS with the size, but i'd have no idea how to properly make it a plugin i could use.

**Comment by LMS0815** [comment]
Yes you need to install Themify Plugin;  Settings would be:
**Selector:** `#terminal-output span.received` or #`terminal-output span.sent`
**CSS-Rule:** `font-size`
**Value:** `14px`

Unfortunately the  included CSS is in favor to any Themify settings. :(

**Comment by LewisSpring** [comment]
Hi there, How come I don’t need the Themeify plugin to use this plugin, but if I wanted to change part of it (eg. The font size) I now need it? Thank you

**edited**: email reply was broken

**Comment by LMS0815** [comment]
For those who like using ThemifyPlugin as a temporary workaround::

**Selector:** `#terminal-output *`
**CSS-Rule:** `font-size`
**Value:** `inherit`

The '*' is doing the trock.

**Comment by LewisSpring** [comment]
I've found two forks: 
https://github.com/trek2710/OctoPrint-TerminalMessaging/blob/master/octoprint_terminalmessaging/static/css/terminalmessaging.css

https://github.com/trek2710/OctoPrint-TerminalMessaging/blob/master/octoprint_terminalmessaging/static/css/terminalmessaging.css

that seem to change the font. ~~**Would I just install these like any other plugin?**~~
_I just tried to install one of them, and it has not worked. Any ideas why_

Thank you

**Comment by jeffeb3** [comment]
I probably should not define the size in this plugin. I'm not sure why I did that in the first place. It might be a hold over from the original css, which was much more txt messaging like.

The best part of this plugin is adding the class names to the items. Anything other than a basic theme should really be handled elsewhere. Font size is probably a step too far.

**Comment by LewisSpring** [comment]
> I probably should not define the size in this plugin. I'm not sure why I did that in the first place. It might be a hold over from the original css, which was much more txt messaging like.
> 
> The best part of this plugin is adding the class names to the items. Anything other than a basic theme should really be handled elsewhere. Font size is probably a step too far.

I think the colors are fine, just the size of the text. Your/jneilliii 's work on this is quite impressive. 

If there was a way to configure the plugin from either a config or settings menu, that would be great.
I wouldn't mind editing the CSS file raw either, but I could not find it in the Octoprint folders.

**Comment by jeffeb3** [comment]
I think I should just remove the size alltogether, it will go back to whatever the default is from octoprint, and people can still adjust it using themify or something like that to adjust the default. I think I should probably also remove the spacing. I really just need the colors and the alignment. I'll play with this when I get a moment and see what it looks like when I remove these extra styles.

**Comment by jeffeb3** [comment]
> In addition I would like to have the _received_ left aligned as it is difficult to read on a wide screen.
> 
> ![image](https://user-images.githubusercontent.com/8235214/97288892-c3ff5500-1846-11eb-9a88-3d636ed680bf.png)

You can do this in themeify as well: 

*selector*: span.sent
*CSS-Rule*: text-align
*value*: left

I am going to make an update to the documentation to include some themeify examples, I think. I suspect a lot of people are going to want to tweak things themselves, and this plugin shouldn't handle everything. It should just add the span classes so other css stuff can manage it.

**Comment by jeffeb3** [comment]
OK. "fixed" in #9 . Now to do the release (hopefully I learned something last time).

**Comment by LewisSpring** [comment]
Thank you!
