### ISSUE TITLE
Request: Button to temporary disable reformatting

### ISSUE THREAD

**Issue by LMS0815** [jeffeb3/OctoPrint-TerminalMessaging#8]
Some button requests for the **terminal window**:

1. Please add a button to disable/enable reformatting (Occasionally I need to have the unmodified output)
2. Please add a button to copy terminal window content to clipboard (To ease working on the details with an external editor).

Thank you.

**Comment by jeffeb3** [comment]
These are outside the scope of this plugin. This plugin's job is just to add some tags to the output so it can be formatted in .css.

It sounds like you would benefit from enabling the serial monitor though. You can just use the text file at that point to do what you want.
